import { BlogType, BlogTypeDetails } from "@/@types/type";
import BlogHeader from "@/components/BlogHeader";
import { getBlogs, getBlogsDetails } from "@/server/blogs";
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import React from "react";
import parse from "html-react-parser";

const BlogDetails = ({
  dataDetails,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Details Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="layout pt-5">
        <section className="flex flex-col items-center">
          <h3 className="text-center text-3xl font-semibold mb-5">
            {dataDetails?.title}
          </h3>
          <div className="mb-6">
            <BlogHeader data={dataDetails} />
          </div>
          <div className="max-w-[500px] text-center leading-normal">
            {parse(dataDetails?.html)}
          </div>
        </section>
      </main>
    </>
  );
};

export default BlogDetails;

export const getStaticPaths: GetStaticPaths = async () => {
  const blog: BlogType[] = await getBlogs();
  return {
    paths: blog.map((item) => ({
      params: {
        id: String(item.id),
      },
    })),
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const id: string | string[] | undefined = context?.params?.id;
  const dataDetails: BlogTypeDetails = await getBlogsDetails(Number(id));
  return {
    props: {
      dataDetails,
    }, // will be passed to the page component as props
    revalidate: 10,
  };
};

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const router = context.query.id;
//   const id: number | undefined | string = Number(router);

// };
